<a href="https://colab.research.google.com/github/PosgradoMNA/Actividades_Aprendizaje-A01794023-Andres_Palacios/blob/main/assignment03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Curso Python Jaime Andres Palacios, matrícula A01794023

## **Module 5 - Working with Numpy Arrays & Simple APIs**

**Numpy 1D Arrays**

Un *"numpy array"* o *"ndarray"* es similar a una lista. Suele tener un tamaño fijo y cada elemento es del mismo tipo. Podemos convertir una lista en una matriz numpy.

In [ ]:
#Llamamos a numpy
import numpy as np

#Creamos la matriz
a = np.array([0,1,2,3,4])
print(a)

#verificamos el atributo de 'a'
print('type(a):',type(a) )

#verificamos el atributo de la data de 'a'
print('a.dtype:',a.dtype)

#verificamos el tamaño de 'a'
print('a.size:',a.size)

#verificamos el número de dimensiones del array 'a' o el rango de la matriz
print('ndim:',a.ndim)

[0 1 2 3 4]
type(a): <class 'numpy.ndarray'>
a.dtype: int64
a.size: 5
ndim: 1


Indexing y slicing methods

In [ ]:
#Creamos el array
c = np.array = ([20,1,2,3,4])
c

[20, 1, 2, 3, 4]

In [ ]:
#modificamos el primer valor la matriz 'c'
c[0]=100
c

[100, 1, 2, 3, 4]

In [ ]:
#probamos modificando el primer ultimo valor la matriz 'c'
c[4]=0
c

[100, 1, 2, 3, 0]

In [ ]:
#Indexamos algunos valores de 'c' en 'd'
d = c[1:4]
d

[1, 2, 3]

In [ ]:
#También podemos asignar nuevos valores a diferentes datos con una sola lines
c[3:5] = 300,400
c

[100, 1, 2, 300, 400]

Basic operations

In [ ]:
#Creamos dos vectores
u=np.array([1,0])
v=np.array([0,1])

#Los sumamos
z = u+v
z

array([1, 1])

**Numpy 2D Arrays**

Podemos crear matrices Numpy con más de una dimensión

In [ ]:
#Creamos un array que contiene tres listas anidadas, cada una de igual tamaño
a = [[11,12,13],[21,22,23],[31,32,33]]
A = np.array(a)
print(A)

print('A.ndim:',A.ndim)
print('A.shape:',A.shape)
print('A.size:',A.size)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
A.ndim: 2
A.shape: (3, 3)
A.size: 9


In [ ]:
#Llamamos valores mediante indexación
A[0][0] #el primer valor cuenta de arriba hacia abajo y el segundo de izquierda a derecha

11

In [ ]:
A[2][2] #el primer valor cuenta de arriba hacia abajo y el segundo de izquierda a derecha

33